### ISSUE TITLE
Web Proxy

### ISSUE THREAD

**Issue by Matthewr7404** [Matthewr7404/FPMS-website#19]

**Comment by NoahBlaut** [comment]
serve a google iframe and proxy it to website using nginx/ngrok "raspberrypi.org/documentation/remote-access/web-server/nginx.md#:~:text=NGINX%20(pronounced%20engine%20x)%20is,scripting%20languages%20such%20as%20PHP"

**Comment by NoahBlaut** [comment]
> serve a google iframe and proxy it to website using nginx/ngrok "raspberrypi.org/documentation/remote-access/web-server/nginx.md#:~:text=NGINX%20(pronounced%20engine%20x)%20is,scripting%20languages%20such%20as%20PHP"

Do we know if an iframe renders on the host or the viewers side?

**Comment by Matthewr7404** [comment]
> > serve a google iframe and proxy it to website using nginx/ngrok "raspberrypi.org/documentation/remote-access/web-server/nginx.md#:~:text=NGINX%20(pronounced%20engine%20x)%20is,scripting%20languages%20such%20as%20PHP"
> 
> Do we know if an iframe renders on the host or the viewers side?

i think that the iframe would embed the site into it

**Comment by NoahBlaut** [comment]
But do you think that the embedded site is rendered on the host server connection or the receiving computers connection. I am pretty sure that the reviving computer processes it so that wouldn't work.
