### ISSUE TITLE
Inspection with browser reveled password to login

### ISSUE THREAD

**Issue by ghost** [Matthewr7404/FPMS-website#2]

**Comment by Dogsaregood20** [comment]
Kk

Noah Blaut

**Comment by Dogsaregood20** [comment]
> there is no way to secure that unless u can find a diffrent code string we wont be able to change it but most ppl wont know

What If We Called On A hidden File To Read The Passwd And compare to typed one

**Comment by Matthewr7404** [comment]
u can try that may just work

**Comment by Matthewr7404** [comment]
what if we use the online database to store it and it checks the database for the compare
