### ISSUE TITLE
Stop people from skipping the index and going straight to maiinpage.html

### ISSUE THREAD

**Issue by Matthewr7404** [Matthewr7404/FPMS-website#20]

**Comment by Matthewr7404** [comment]
we could use a variable that is the fact they are logged in and if that variable is false it will send them back to index.html

**Comment by Matthewr7404** [comment]
other than that i dont know

**Comment by Matthewr7404** [comment]
maybe we can look into the code of other password protected sites???

**Comment by NoahBlaut** [comment]
Set a local storage object to a date code and check for that code on all pages using js script include. Every day the code is changed with the date logging them out after one day at 00:00. The code would consist of a date encrypted using a hash. We assign the local storage object after logging in.
