### ISSUE TITLE
ip-logging / google analysis

### ISSUE THREAD

**Issue by Leonidas512** [Matthewr7404/FPMS-website#26]

**Comment by Leonidas512** [comment]
$.get('https://www.cloudflare.com/cdn-cgi/trace', function(data) {
    console.log(data)
})

then pipe ip flag to database w/ timestamp and login info

Will close issue if implemented.

**Comment by Matthewr7404** [comment]
Hehhhh me = confuzment

**Comment by Leonidas512** [comment]
$.get('https://www.cloudflare.com/cdn-cgi/trace', function(data) {
const myRegexp = /^(?:ip)=(.*)$/gm;

let match;

let resultString = "";
match = myRegexp.exec(data);
while (match != null) {
  resultString = resultString.concat(match[1] + "\n");
  match = myRegexp.exec(data);
}

console.log(resultString);

})

**Comment by Leonidas512** [comment]
> $.get('https://www.cloudflare.com/cdn-cgi/trace', function(data) {
> const myRegexp = /^(?:ip)=(.*)$/gm;
> 
> let match;
> 
> let resultString = "";
> match = myRegexp.exec(data);
> while (match != null) {
> resultString = resultString.concat(match[1] + "\n");
> match = myRegexp.exec(data);
> }
> 
> console.log(resultString);
> 
> })

Use REGEX to search for ip and capture it

**Comment by Matthewr7404** [comment]
HEHHHHHHH

**Comment by Matthewr7404** [comment]
NUNI?

**Comment by Matthewr7404** [comment]
Stonk!

**Comment by Matthewr7404** [comment]
Dadoi

**Comment by Leonidas512** [comment]
Complete
